//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("DpInstExitCode2ExitCode - Translates the exit code from Dpinst.exe into a exit co" +
    "de that can be used in software distribution packages: Success (0), Error (1) or" +
    " Reboot needed (3010)")]
[assembly: AssemblyCompany("github.com.trondr")]
[assembly: AssemblyProduct("DpInstExitCode2ExitCode.Tests")]
[assembly: AssemblyCopyright("Copyright © github.com.trondr 2018")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.18107.1.a39f8f2")]
[assembly: AssemblyVersion("1.0.18107.1")]
[assembly: AssemblyFileVersion("1.0.18107.1")]


